#!/usr/bin/env node
/* eslint-disable no-console */
// Помощник для черновика changelog.ts из git log.
// pnpm changelog:draft [--since <ref>]
// Без --since — берёт коммиты с последнего git tag.
// Выводит TS-объекты для копипаста в apps/web/src/data/changelog.ts.
// Перепиши before/after человеческим языком — raw commits подсунуты комментариями.

import { execSync } from "node:child_process";

function arg(name) {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : null;
}

function git(cmd) {
  try {
    return execSync(cmd, { encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

const since = arg("--since") || git("git describe --tags --abbrev=0");
if (!since) {
  console.error("Не удалось определить --since. Передай флаг явно: --since <tag-or-sha>");
  process.exit(1);
}
console.error(`# Черновик changelog с ${since} (используй stdout)`);

const log = git(
  `git log ${since}..HEAD --pretty=format:"%h|%ad|%s" --date=short`,
);
if (!log) {
  console.error("Нет новых коммитов с момента", since);
  process.exit(0);
}

const SCOPE_TO_AREA = {
  rentals: "Аренды",
  rental: "Аренды",
  swap: "Аренды",
  dashboard: "Дашборд",
  documents: "Документы",
  docs: "Документы",
  document: "Документы",
  contract: "Документы",
  editor: "Документы",
  clients: "Клиенты",
  client: "Клиенты",
  apply: "Заявки",
  applications: "Заявки",
  fleet: "Скутеры",
  scooter: "Скутеры",
  park: "Парк",
  service: "Ремонты",
  repair: "Ремонты",
  damage: "Ремонты",
  topbar: "Общее",
  drawer: "Дашборд",
  modals: "Общее",
  ui: "Общее",
  ux: "Общее",
  api: "Общее",
};

const TYPE_TO_CATEGORY = {
  feat: "Новое",
  fix: "Исправление",
  ui: "Дизайн",
  style: "Дизайн",
  ux: "Улучшение",
  perf: "Улучшение",
};

// Игнорируем технические коммиты, заказчику не интересные.
const SKIP_TYPES = new Set(["chore", "docs", "build", "ci", "test", "refactor"]);

const groups = new Map();

for (const line of log.split("\n")) {
  const [sha, date, ...rest] = line.split("|");
  if (!sha) continue;
  const subject = rest.join("|");
  const m = subject.match(/^([a-z]+)(?:\(([^)]+)\))?:\s*(.*)$/i);
  if (!m) continue;
  const [, type, scopeRaw, title] = m;
  const lc = type.toLowerCase();
  if (SKIP_TYPES.has(lc)) continue;

  const scope = (scopeRaw || "").split(",")[0]?.trim().toLowerCase();
  const area = SCOPE_TO_AREA[scope] || "Общее";
  const category = TYPE_TO_CATEGORY[lc] || "Улучшение";

  const key = `${date}::${area}::${category}`;
  if (!groups.has(key)) {
    groups.set(key, { date, area, category, commits: [] });
  }
  groups.get(key).commits.push({ sha, title: subject.trim() });
}

const ordered = Array.from(groups.values()).sort((a, b) =>
  a.date < b.date ? 1 : -1,
);

console.log("// AUTOGENERATED DRAFT — перепиши title/before/after человеческим языком,");
console.log("// затем вставь в apps/web/src/data/changelog.ts.");
console.log("");

for (const g of ordered) {
  const slugBase = `${g.date}-${g.area.toLowerCase()}-TODO`;
  console.log(`{`);
  console.log(`  id: ${JSON.stringify(slugBase)},`);
  console.log(`  date: ${JSON.stringify(g.date)},`);
  console.log(`  category: ${JSON.stringify(g.category)},`);
  console.log(`  areas: [${JSON.stringify(g.area)}],`);
  console.log(`  title: "TODO: одна короткая фраза",`);
  console.log(`  before: "TODO: что было не так / что бесило",`);
  console.log(`  after: "TODO: что теперь",`);
  console.log(`  // raw commits:`);
  for (const c of g.commits) {
    console.log(`  // ${c.sha} ${c.title}`);
  }
  console.log(`},`);
  console.log("");
}
